package com.spacestudent.ssapi.util.constants;

public enum ReservationConstants {

	WALLET_NOT_FOUND,
	AMOUNT_INVALID,
	WALLET_NOT_UPDATED,
	RESERVATION_NOT_CREATED,
	RESERVATION_CREATED,
	RESERVATION_NOT_FOUND,
	RESERVATION_ALREADY_LIFTED,
	WALLET_MIN_VALUE_NULL,
	WALLET_MIN_VALUE_INFERIOR_AMOUNT,
	BALANCE_NOT_REDUCABLE,
	MERCHANT_CODE_NOT_FOUND,
	AGENT_NOT_FOUND,
	TRANSFER_FAILED,
	TRANSFER_SUCCEEDED,
	RESERVATION_LIFTED,
	RESERVATION_PENDING;
	
}
